[package]
name = "teo"
version = "0.1.0"
edition = "2021"
description = "Next-generation web framework for Rust, Node.js and Python."
license = "Apache-2.0"
build = "build.rs"
homepage = "https://teocloud.io"
documentation = "https://teocloud.io/docs"
repository = "https://github.com/teocloud/teo"

[dependencies]
teo-result = "0.1.0"
teo-teon = "0.1.0"
teo-parser = "0.1.0"
teo-runtime = "0.1.0"
teo-sql-connector = "0.1.1"
teo-mongodb-connector = "0.1.1"
teo-generator = "0.1.0"
actix-web = "4.4.1"
actix-http = "3.5.1"
actix-multipart = "0.6.1"
actix-files = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
chrono = { version = "0.4.31", features = ["serde"] }
random-string = "1.0"
futures = "0.3"
futures-util = "0.3"
regex = "1.10.2"
tokio = { version = "1.0", features = ["full"] }
url = "2.5"
bcrypt = "0.15.0"
uuid = { version = "1.6", features = ["v4", "fast-rng"] }
cuid2 = "0.1.0"
cuid = "=1.2.0"
bigdecimal = "=0.3.1"
async-recursion = "1.0.5"
async-trait = "0.1.74"
num-integer = "0.1.45"
maplit = "1.0.2"
key-path = "0.2.0"
once_cell = "1.19"
indexmap = "2.1.0"
itertools = "0.12.0"
array_tool = "1.0.3"
snailquote = "0.3.1"
clap = { version = "4.4.11", features = ["derive"] }
path-absolutize = "3.1.1"
dotenvy = "0.15.7"
rand = "0.8.5"
educe = "0.5.9"
colored = "2.1.0"
bson = { version = "2.7.0", features = ["chrono-0_4", "serde_with"] }

[dev-dependencies]
serial_test = "2.0.0"
test-helpers = "0.2.3"
reqwest = { version = "0.11", features = ["json", "blocking"] }

[build-dependencies]
rustc_version = "0.4.0"

[features]
#default = ["data-source-mongodb", "data-source-mysql", "data-source-postgres", "data-source-sqlite", "data-source-mssql"]
#data-source-mongodb = ["mongodb", "bson"]
#data-source-mysql = ["quaint-forked"]
#data-source-postgres = ["quaint-forked"]
#data-source-sqlite = ["quaint-forked"]
#data-source-mssql = ["quaint-forked"]
